#ifndef SYSTEM_DEFINITIONS_H
#define SYSTEM_DEFINITIONS_H

#define N 9
#define CAMERA_SAMPLING_INTERVAL_MS 120
#define SENSOR_SAMPLING_INTERVAL_MS 60

#define TIME_STEP_MS 60

// GPIO Channel Definitions
#define BUTTONS_CHANNEL 1
#define BUTTONS_DEVICE_ID XPAR_GPIO_1_DEVICE_ID

#define LEDS_CHANNEL 1
#define LEDS_DEVICE_ID XPAR_GPIO_0_DEVICE_ID



#endif // SYSTEM_DEFINITIONS_H
